checkstyle/eclipse-cs

- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.core/pom.xml
- net.sf.eclipsecs.ui/pom.xml
- pom.xml
The tycho-source-plugin version was overridden in the children of the
aggregator instead of inheriting the version. This was necessary because
the parent version definition had a typo (tycho.version instead of
tycho-version). After fixing the typo, the overrides are not necessary
anymore.
> fix Maven warnings

- LICENSE
Github uses a license file at repository root level to display license information directly besides the project. License text was given by github tooling (i.e. I only selected LGPL 2.1 from a list of choices).
See https://github.com/checkstyle/eclipse-cs/community, where things like license and code of conduct for a project are described.
> Create LICENSE at repository root level

- net.sf.eclipsecs.doc/.derived
When using the AutoDeriv plugin, this automatically set the "docs"
folder as derived, thereby excluding it from file search etc.
Unfortunately the "derived" flag is not part of the workspace itself
(therefore it cannot be versioned).
Developers not using the AutoDeriv plugin are not affected at all by
this change.
> releng: have AutoDeriv config for docs folder

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationWorkingSetEditor.java
When the preference or properties page is opened, no configuration is
selected, therefore the buttons beside the table should be disabled.
> disable configuration buttons without config selected

- net.sf.eclipsecs-feature/feature.xml
That way with the next update installation (from SF) all plugins learn
the new update site automatically and check for further updates from
github.
> point feature to new update site

- net.sf.eclipsecs.doc/src/main/resources/partials/index.html
- net.sf.eclipsecs.doc/src/main/resources/partials/install.html
Have all versions from Juno to Oxygen in all places mentioning
installation. As an alternative, we could simplify this to "...into a
running Eclipse (Juno or newer version) workspace..."
> unify installation instructions

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/Module.java
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/plugin.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/Messages.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/CheckstylePropertyPage.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/CheckstyleMarkerPropertyTester.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/MarkerPropertyPage.java
This adds a new property page for checkstyle issues, which show the
check and module of the issue.
This is incomplete, since the retrieved module and key need to be
localized.
> #32: new checkstyle marker property page

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
- net.sf.eclipsecs.sample/src/net/sf/eclipsecs/sample/checks/MethodLimitQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/FixCheckstyleMarkersAction.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/blocks/AvoidNestedBlocksQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/blocks/NeedBracesQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/DefaultComesLastQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/FinalLocalVariableQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/MissingSwitchDefaultQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/StringLiteralEqualityQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/design/DesignForExtensionQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/design/FinalClassQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/misc/ArrayTypeStyleQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/misc/FinalParametersQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/modifier/ModifierOrderQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/modifier/RedundantModifierQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/data/MarkerStat.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/data/Stats.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/AbstractStatsView.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/GraphPieDataset.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/GraphStatsView.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/MarkerStatsView.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilter.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilterDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/regex/RegExContentAssistProcessor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/EnhancedCheckBoxTableViewer.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/EnhancedTableViewer.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/ITableComparableProvider.java
First I fixed all warnings that could be fixed by adding generic type
arguments. Only afterward I silenced the remaining warnings (basically
in all the AST visit() methods which operate with the non-generic JDT
API). Additionally, all adapter related assignments have been silenced, since we still compile against the non-generic adapter implementation.
> fix or silence generics warnings

- net.sf.eclipsecs.core/plugin.xml
- net.sf.eclipsecs.core/schema/checkstyleAddonProvider.exsd
- net.sf.eclipsecs.core/schema/configtypes.exsd
- net.sf.eclipsecs.core/schema/configurations.exsd
- net.sf.eclipsecs.core/schema/filters.exsd
- net.sf.eclipsecs.core/schema/saveFilters.exsd
- net.sf.eclipsecs.ui/plugin.xml
- net.sf.eclipsecs.ui/schema/checkstyleQuickfixProvider.exsd
- net.sf.eclipsecs.ui/schema/configtypesui.exsd
- net.sf.eclipsecs.ui/schema/filtereditors.exsd
* remove empty [...] sections, they are otherwise part of the generated
documentation
* replace link tags by code tags, since link tags lead to validation
errors and are not rendered
* use descriptive names for the extension points instead of repeating
their IDs
* fix the wrong occurrences of "filters" as extension point schema IDs.
* typos
None of these changes influences the extension point registry. All
relevant IDs are still the same as before, so extenders continue to work
without modification.
> fix multiple extension declaration issues

- net.sf.eclipsecs.branding/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.doc/META-INF/MANIFEST.MF
- net.sf.eclipsecs.sample/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
https://dzone.com/articles/automatic-module-name-calling-all-java-library-maintainers
This is basically getting added to each and every Eclipse plugin during the last weeks and months.
> automatic module name for java 9 compatibility

- net.sf.eclipsecs.branding/.project
- net.sf.eclipsecs.checkstyle/.project
- net.sf.eclipsecs.core/.project
- net.sf.eclipsecs.sample/.project
- net.sf.eclipsecs.ui/.project
When m2eclipse was rebranded as m2e, a new nature (namely the m2e nature
directly above the deleted lines) was created. This one can be deleted
to avoid a warning in Photon.
> remove outdated natures

- net.sf.eclipsecs.doc/src/main/resources/partials/builtin-config.html
- net.sf.eclipsecs.doc/src/main/resources/partials/custom-checks.html
- net.sf.eclipsecs.doc/src/main/resources/partials/custom-filters.html
- net.sf.eclipsecs.doc/src/main/resources/partials/extensions.html
If a line break is inside a pre block, it will be rendered as is,
therefore leading to empty lines at the begin or end of some of the
example code blocks in the documentation.
At the same time, this also updates an outdated git URI in the documentation
> remove empty lines in example code

- net.sf.eclipsecs.core/schema/configurations.exsd
- net.sf.eclipsecs.core/schema/filters.exsd
This copies the existing example extensions from the documentation into
the extension point declaration itself. This way the examples are
available directly when creating the extension in PDE.
> Add extension point implementation examples

- net.sf.eclipsecs.checkstyle/pom.xml
The new checkstyle source naming scheme was not used in the Maven build.
> Fix the Maven build

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties
The "Up" button in the enhanced configuration is labeled "\ Up"
accidentally. Also fix some other typos in the same file.
> fix wrong button label

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleBuilder.java
Since Eclipse Photon or Oxygen users can enable parallel building of the
workspace. However, parallel building requires all existing project
builders to implement a useful scheduling rule. If builders don't
implement that method, they automatically lock the workspace root.
A simple and still safe implementation for checkstyle is to lock only
the currently analyzed project. That allows all other builders to run on
the remaining projects in parallel.
See https://de.slideshare.net/mickaelistria/parallel-builds-in-eclipse-ide-workspace
for more technical background.
> allow parallel building with checkstyle

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/Messages.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
Show the version as the preference page "description" field. The displayed version is the one of the embedded JAR, independent of the version of the Eclipse plugin (e.g. for the current plugin version 8.12 it shows 8.13 correctly).
> Fix #120: checkstyle version in preferences

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/CheckstyleConfigurationFile.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/ConfigurationType.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/filters/FilesOlderThanOneDayFilter.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/filter/CheckFileOnOpenPartListener.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/CheckstyleMarkerPropertyTester.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/SimplifyBooleanReturnQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilter.java
This fixes the checkstyle violations that only have a small number of
occurrences:
* wrong Javadoc see tag
* not commented throws javadoc tags
* tabs versus space
> Fix some checkstyle violations

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationReader.java
Replace the current DTD registration with a verbatim copy from the main
checkstyle code to avoid further deviations.
The old code had one wrong DTD name, one duplicate entry without the
needed differentiation between checkstyle/puppycrawl, and it missed some
variants of the current 8 combinations.
> Fix #114: Correct DTD names

- net.sf.eclipsecs.branding/META-INF/MANIFEST.MF
- net.sf.eclipsecs.branding/about.properties
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.doc/META-INF/MANIFEST.MF
- net.sf.eclipsecs.sample/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
* Looking at the plugins list of the checkstyle feature shows a wild mix
of plugin names. Therefore make them more unique and more simple. Also
shorten the provider name, since it isn't displayed nicely in the
Eclipse UI due to its size.
* Also remove "plugin" from the branding. That word doesn't add any
information and is even confusing, when being used for a feature name.
* Remove iText from components mentioned on about page, that library is
not used in current code.
> unify and simplify branding

- net.sf.eclipsecs.core/core.properties
In recent Eclipse versions, project natures can be seen in the project
properties on the "Project natures" tab. Projects with enabled
Checkstyle list "CheckstyleNature" there. This change fixes the label.
This has no impact on the nature id and all the code testing for that
nature id.
> Fix the Checkstyle nature name

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationWorkingSetEditor.java
After creating a new configuration, the user cannot immediately
configure it, because the new configuration is not selected in the table
of existing configurations (and therefore all the related buttons are
disabled).
This change automatically selects the newly created configuration, and
therefore users can immediately use the "Configure" button.
> Select newly created configurations

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/BuiltInConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ExternalFileConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ICheckConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ProjectConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/RemoteConfigurationEditor.java
When a configuration editor is opened, no control has the focus.
Keyboard users must explicitly use tab for being able to input
something. Let us always focus the name input field instead.
Unfortunately the name field is implemented 5 times in 5 different
configuration editors, therefore the same change is applied 5 times.
> Focus name field in configuration editor

- docs/partials/filters.html
- net.sf.eclipsecs.doc/src/main/resources/partials/filters.html
That filter was added some time ago, but was not yet documented on the
website and in the online help.
src/main/resources is the original change for the eclipse online help,
docs/partials is generated from a local maven build for the website.
both must be committed.
I must admit I'm not sure if an additional change is necessary for the github pages branch. But if so, it will happen automatically when Lars releases a new version.
> Add documentation for "files older than a day" filter

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
Avoid an NPE when matching on the rule description. For completeness,
apply the same null check on the name fields also, although those should
never return null.
> avoid NPE in rule filter (fixes #153)

- net.sf.eclipsecs.branding/META-INF/MANIFEST.MF
If an Eclipse feature specifies a branding plugin, then the icon, name
and some other meta data of that plugin are shown as "branding" of the
feature in the Eclipse about dialog. Therefore that specific plugin
should not be called "... branding".
Without this change, the about dialog shows the following:
> remove "Branding" from feature name in about dialog

- .settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs-feature/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs-updatesite/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.branding/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.core/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.doc/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.sample/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.target/.settings/org.eclipse.core.runtime.prefs
- net.sf.eclipsecs.ui/.classpath
- net.sf.eclipsecs.ui/.settings/org.eclipse.core.runtime.prefs
Two of the bundles contain nested tests. However, those have never been
available in Eclipse itself (only in Maven), since they are not on the
classpath of the plugins.
With this change the tests are shown as a separate test source folder
and can be run directly from eclipse. Also potential compiler errors in tests will now be visible immediately (while they were only visible in the maven build output before).
It is not possible to accidentally mix test and main sources, because Eclipse has a main/test classpath
separation (that's the additional attribute "test" with value "true" in the classpath entry).
> fix test classpath

- pom.xml
This may fix the Travis build with Java 12, since Tycho 1.5 supports
Java 12. See https://wiki.eclipse.org/Tycho/Release_Notes/1.5#ECJ_update
> Upgrade Tycho to 1.5.1

- .travis.yml
- pom.xml
Use the most recent version of Tycho during builds. Since it no longer
supports JDK 12, also upgrade the build matrix to JDK 13 and document
the Java versions of the build matrix.
> Use Tycho 1.6.0 and JDK 13 in tests

- net.sf.eclipsecs.target/.project
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
- net.sf.eclipsecs.target/readme.md
- net.sf.eclipsecs.target/readme.txt
The TPD editor plugin is hosted at a different location. Update the
comments where to find it, and regenerate the target platform. Also
enable the Xtext builder on the project.
There are no actual functional changes, this is just housekeeping.
> Update target platform documentation

- net.sf.eclipsecs.doc/src/main/resources/partials/index.html
- net.sf.eclipsecs.doc/src/main/resources/partials/install.html
* remove wrong mentioning of Indigo as supported version
* don't list all Eclipse releases, to avoid the need for updating files
on every new Eclipse release
* use "Juno or higher version" instead of ">Indigo", since that is
easier to understand for end users
> Fix minimum Eclipse version documentation

- pom.xml
* enforce latest Maven 3.6.3 (it is available on Travis, according to
their specs)
* use latest junit 4 (but not yet junit 5)
* remove separate version for tycho-extras (tycho-extras has been merged
with tycho in 1.6, so they are definitely always versioned together now,
even though the maven group id is still different)
> Upgrade Maven dependencies

- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
The Maven POM configures Java 8 as source and target level during
compilation already. However, in Eclipse the target platform definition
does not specify the JRE level, which can lead to inconsistencies during
development in seldom cases.
Most developers should not see any difference from this change, since
they should be using a JRE 8 for Eclipse CS development anyway.
> Configure target platform for Java 8

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckerFactory.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleBuilder.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/modifier/ModifierOrderQuickfix.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/GraphPieDataset.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/GraphStatsView.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/MarkerStatsView.java
Boxing constructors of primitive types are deprecated in newer versions
of Java and should not be used.
> Replace boxing constructors

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
When updating the list of modules matching the given text filter,
disable redrawing the underlying OS control. Otherwise there is a
flickering effect, since the control is redrawn for every item being
processed by the filter by default.
With redrawing disabled, the control is only drawn once all items have
been filtered, and there is no more flickering.
> avoid flickering during filter update

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/ChecksTest.java
- net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/utils/XmlUtil.java
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
- net.sf.eclipsecs.ui/.classpath
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/AbstractQuickfixTestCase.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/blocks/AvoidNestedBlocksTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/blocks/NeedBracesTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/DefaultComesLastTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/EmptyStatementTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/ExplicitInitializationTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/FinalLocalVariableTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/MissingSwitchDefaultTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/RequireThisTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/SimplifyBooleanReturnTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/coding/StringLiteralEqualityTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/design/DesignForExtensionTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/design/FinalClassTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/misc/ArrayTypeStyleTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/misc/FinalParametersTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/misc/UncommentedMainTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/misc/UpperEllTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/modifier/ModifierOrderTest.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/modifier/RedundantModifierTest.java
- pom.xml
Change all dependencies for Maven and Eclipse from JUnit 4 to JUnit 5
and convert all the JUnit API to JUnit Jupiter. This allows running the
existing tests as JUnit 5 tests in Maven and Eclipse (given a recent
Eclipse IDE).
> Use JUnit 5

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/blocks/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/pom.xml
Fixes #237.
Checking "INTERFACE_DEF token support in RightCurlyCheck".
> Issue #237: update to Checkstyle 8.34

- .gitignore
- .travis.yml
- build-patch-filter.sh
- config/checkstyle.properties
- config/checkstyle_checks.xml
- config/checkstyle_sevntu_checks.xml
- config/import-control-test.xml
- config/import-control.xml
- config/java.header
- config/java_regexp.header
- config/sevntu_suppressions.xml
- config/suppressions.xml
- pom.xml
Issue #251: ci:build patch-filter jar buring a build
this refers to https://github.com/checkstyle/eclipse-cs/pull/246
> Issue #251: ci:build patch-filter jar buring a build

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/FormatterConfigWriter.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/XmlProfileWriter.java
Instead of using the broken internal APIs, simply write directly into XML files that the user can then import.
> Fix #107: Write format/cleanup profiles to XML files within project

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
with  the internalName:
* we easy search on web, such as https://checkstyle.sourceforge.io/checks.html
* and SuppressWarnings with the internalName when neeed
ie:
```
@SuppressWarnings({"checkstyle:WriteTag"})
```
> prefer using internalName in violation message

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
Fixes #273.
Demonstrating new LambdaBodyLength check functionality:
> Issue #273: update to Checkstyle 8.37

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
Fixes #275.
Demonstrating new JavadocMissingLeadingAsterisk check functionality:
> Issue #275: update to Checkstyle 8.38

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/design/checkstyle-metadata.properties
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/design/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/ChecksTest.java
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
Fixes #277.
This one was a bit trickier because the metadata of DesignForExtension changed. 
We're not actually using the metadata that's in the plugin anymore, so I just decided to remove the check from the tests and delete its metadata. We'll have to do that for all checks eventually. Screenshots below to show that it uses the metadata from the checkstyle jar.
Also demonstrating new check RecordComponentName.
> Issue #277: update to Checkstyle 8.40

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
Fixes #287.
Verified the new behavior of UnnecessaryParentheses:
> Issue #287: update to Checkstyle 8.42

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/ChecksTest.java
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
Fixes #297.
Verified UnnecessaryParentheses false positives are gone.
> Issue #297: update to Checkstyle 8.43

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
Issue #316
This seems to resolve the issue for me. I would need an explanation on how to verify the configuration menu works as intended, especially with modules with properties from sevntu.
I believe the issue is we are preventing third parties from creating their own custom group. Sevntu names it's group `SevNTU checks`. We were only allowing names `Other` in.
This may have been intended to prevent third parties from adding their own checks to Checkstyle's main groups?
Screenshot of test usage:
Screenshot clearly shows highest eclipse-cs version and sevntu checks with descriptions. I was concerned that nothing was showing on the right hand side of the dialog under "Configured modules for group" and wanted to know how to test this more.
> Issue #316: Allow third party checks to have a custom group name

- .derived
- net.sf.eclipsecs-feature/.derived
- net.sf.eclipsecs-updatesite/.derived
- net.sf.eclipsecs.branding/.derived
- net.sf.eclipsecs.checkstyle/.derived
- net.sf.eclipsecs.core/.derived
- net.sf.eclipsecs.sample/.derived
- net.sf.eclipsecs.target/.derived
- net.sf.eclipsecs.ui/.derived
Eclipse has the ability of not showing generated or otherwise derived resources by explicitly marking them as derived. That simplifies file searches. Files can be marked automatically using an additional plugin. Developers not using that plugin will not notice any difference from this change.
> infra: automatically mark target folders derived

- .travis.yml
Use the long versions of the options since others reading the file might not know the short versions. If the build fails on the no-progress option, then it needs to be removed. That one is only available in recent maven versions.
> infra: disable maven download messages

- .travis.yml
This reverts a part of my previous PR. In early Maven versions the batch-mode option was the only way to suppress download messages. However, since Maven 3.5 it also suppresses the ANSI escape characters that cause colored output in the shell. That's why the current Travis console is no longer colored after the previous commit.
Long story short: On recent maven versions, only the -ntp option should be used, but not the batch-mode option. (I only learned this yesterday evening, otherwise I would have avoided adding it in the first place)
> infra: re-enable colored output on Travis

- net.sf.eclipsecs-feature/pom.xml
- pom.xml
The previously separate tycho-source-feature-plugin functionality is included in tycho-source-plugin meanwhile:
https://github.com/eclipse-tycho/tycho/blob/master/RELEASE_NOTES.md#tycho-source-feature-generation-moved-from-tycho-extras-to-tycho-core. Replacing it removes one warning from the Maven build.
Also move the configuration into the parent POM, since it is independent of the specific feature being built (i.e. could be reused if another feature would be built).
And remove some commented out configuration of the p2-metadata plugin. We wouldn't want to use it with those configuration values anyway.
Verified the source feature in the update site is identical to what it was before. BTW: I'm also committer on the Tycho project. :)
> ci: replace tycho-source-feature-plugin

- net.sf.eclipsecs.ui/.classpath
- net.sf.eclipsecs.ui/pom.xml
- pom.xml
Re-enable the UI plugin tests. Locally they work fine both in the Eclipse test runner as well as in Maven.
> infra: re-enable eclipsecs.ui tests

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationPropertiesDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/ResolvablePropertiesDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/ResolvablePropertyEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/RuleConfigurationEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/FileMatchPatternEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/FileSetEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilterDialog.java
Search for all classes derived from TitleAreaDialog and disable help in their constructor. Also used the type hierarchy to verify all classes had been found.
> Issue #391: disable context help

- pom.xml
Fix the warnings `[WARNING] artifact
foo:bar:p2metadata:10.3.3-SNAPSHOT already attached, replace previous instance` by disabling the default metadata generation. Unfortunately this extra step is necessary when creating source features, since the attaching of metadata needs to be delayed then.
> ci: fix warnings in maven console

- pom.xml
Eclipse still warns about not being able to map the maven clean goal to the Eclipse build lifecycle. Since that maven goal is not necessary for a successful build, we can ignore it inside Eclipse, similar to the other goals of the resources plugin that have already been ignored.
> infra: fix Maven warning in Eclipse

- .gitignore
While the build is running, Tycho generates several temporary files outside of the Maven target directories. If developers refresh their staging view during the build, they may be confused by those temporary files. Therefore gitignore them.
> infra: gitignore temporary files of Tycho

- pom.xml
Completes the verify CS version upgrade to 10.4 which is what patch-filters relies on.
Blocked until sevntu actually releases which is coming.
> infra: upgrade checkstyle verify to 10.4

- net.sf.eclipsecs.doc/pom.xml
The documentation generation has 2 different target directories:
* root/docs for the website
* root/net.sf.eclipsecs.docs/docs for the online help
Care must be taken to not confuse them in scripts.
> fix #411: broken online help

- pom.xml
Due to a bug in Tycho the path towards target platform files is not normalized. Therefore a/../target and b/../target are considered different files, even though they are in fact the same.
As a workaround use a path relative to the directory where the maven build was started in, which is identical for all maven modules. This is typically not recommended, because it would not work when building a single module only, but that doesn't work anyway in this project (due to the checkstyle maven config properties resolution).
> Infra: Avoid repeated target file resolution

- net.sf.eclipsecs.target/Maven update check.launch
- net.sf.eclipsecs.target/Maven verify.launch
These launch configs can be used to run Maven from within Eclipse, without a separate shell. Update them in these aspects:
* have an additional launch config for "mvn verify"
* update all launch configs to the latest serialization format (including new preferences)
* disable parallel build for the update related launches, since those maven plugins are not thread-safe
* have already the next version number in the update-version launch config (this is fully working!)
There are no functional changes for the build, this only affects Eclipse developers working on the eclipse-cs code.
> infra: update maven launch configs

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetAbstractBase.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetString.java
Convert between MessageFormat and plain text when initializing/leaving the UI. Verified by editing the configuration multiple times.
> Issue #417: Escape/unescape custom messages

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/actions/ConfigureProjectFromBluePrintAction.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ProjectConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/filter/PackageFilterEditor.java
The previous PR linked to the issue was not complete. I found 3 more dialogs with context help enabled, and disabled it the same way as before.
> Issue #391: disable dialog context help

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/RuleConfigurationEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetRegex.java
JFace text controls have a separate message property to give hints for the expected input into a text field. Programmatically setting the actual control text instead is a bad idea since it can lead to the user actually editing that hint.
before the change its possible to edit the hint, since it's the actual widget text:
after the change the widget itself shows the hint only if the input is empty:
> don't use input text for filter hints

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleBuilder.java
@Calixte I've slightly reworked your change, so it will still remove the previous problem markers from the file, even if it is not scanned. Otherwise we might see outdated errors on files that transitioned from compilable to uncompilable.
> Issue #172: skip files with java errors

- net.sf.eclipsecs.checkstyle/pom.xml
If multiple zip files are available in the local directory (from previous builds of older releases), the previous code might choose a wrong outdated version. Just use the known file name from the download to avoid that.
> Avoid wrong checkstyle library being unpacked

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/CheckstylePlugin.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPlugin.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/data/MarkerStat.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/data/Stats.java
> Issue #440: resolves UselessSuperCtorCallCheck

- README.md
Updates the travis CI link in the readme as it doesn't work for me. It takes me to a page that says "This repository was migrated and is now building on travis-ci.com".
Used similar links to main repo.
> minor: updates travis ci link in readme

- config/sevntu_suppressions.xml
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/CheckConfigurationFactory.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/Module.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/ConfigurationType.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/StandardPropertyResolver.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/RuleMetadata.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/ProjectConfigurationFactory.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/CheckstyleTransformer.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/FormatterTransformer.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPlugin.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationWorkingSetEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/RuleConfigurationEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetAbstractBase.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetRegex.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/ComplexFileSetsEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/FileSetEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/SimpleFileSetsEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/filter/PackageFilterEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/AbstractASTResolution.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/data/CreateStatsJob.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/AbstractStatsView.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/EnhancedCheckBoxTableViewer.java
> Issue #440: resolves CustomDeclarationOrder

- .travis.yml
Travis can only use arch `ppc64le` otherwise we get charged. Travis will shutdown when we use up all our credits.
We won't know if this will continue working once travis returns, but we need this removed regardless.
> config: removes custom arch to avoid credit usage

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
Methods are never accessed outside the class and do not need to be public.
> minor: locks down method access in MetadataFactory

- pom.xml
Fix #475
This way Tycho automatically includes direct _and_ transitive dependencies in the update site. That is more than just the missing libraries, it includes every plugin needed when installing Eclipse-CS (that is, down to the actual Eclipse workbench and similar plugins).
The amount of data used during an installation does not change. The main change is that during installation all _needed_ plugins are found in the Eclipse-CS update site _as such_ while previously other known Eclipse repositories would be contacted to look for the missing transitively required bundles. This setting should have been used before, as it is generally good practice to have self-contained update sites.
Users can now also uncheck the checkbox "Contact all update sites to find required software", which will …
> Fix #475: include transitive dependencies

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/AbstractCheckJob.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/AuditorJob.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/RunCheckstyleOnFilesJob.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPlugin.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPluginImages.java
Jobs being shown in the progress view can style the icon next to the progress bar. The git plugin uses that to show an icon matching the current git operation, spotbugs and some others show their specific icon. Let's also have the checkstyle icon next to the running checkstyle jobs so that it can be recognized more easily in a mix of running jobs.
Looks like this:
> have progress icon for checkstyle jobs

- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.target/net.sf.eclipsecs.partial.maven.target
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/ResolvablePropertiesDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/ResolvablePropertyEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/RuleConfigurationEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ExternalFileConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/InternalConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ProjectConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/RemoteConfigurationEditor.java
- net.sf.eclipsecs.ui/test/net/sf/eclipsecs/ui/quickfixes/AbstractQuickfixTestCase.java
Before this change eclipse-cs used the Google Guava packages exported by the checkstyle core library, and even reexported them for other bundles. Since those re-exports were using the checkstyle library version, they might lead to version confusion in other bundles importing the same packages (since Guava has completely different version numbers than the checkstyle core library). Also updating the Guava version in the checkstyle library could easily lead to eclipse-cs breaking on next update due to this coupling.
Remove those re-exports from eclipse-cs and make every bundle manage its own package imports instead.
Remove the Guava dependency in eclipsecs.ui. It was only used for Guava Strings, and that can be replaced with the much smaller Apache Commons Lang3, therefore also getting rid …
> remove reexports of checkstyle core library

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
When adding multiple modules to a configuration, the module configuration dialog is opened for each of them. If the user did that on accident, she had to go through as many dialogs as modules were selected.
With this change after the first cancellation of any dialog, no more dialogs are opened and no more rules are added.
Verified by manual testing. The implementation must use the return value (and not just cancel the iterator) because adding modules is implemented recursively, and we also want to cancel any previous levels of the recursion.
> Issue #492: abort opening more module dialogs after cancel

- docs/dtds/checkstyle-metadata_1_0.dtd
- docs/dtds/checkstyle-metadata_1_1.dtd
- docs/partials/custom-checks.html
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/annotation/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/blocks/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/design/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/header/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/imports/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/indentation/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/metrics/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/modifier/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/naming/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/regexp/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/sizes/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/whitespace/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checkstyle-metadata_1_0.dtd
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checkstyle-metadata_1_1.dtd
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/filefilters/checkstyle-metadata.xml
- net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/filters/checkstyle-metadata.xml
- net.sf.eclipsecs.doc/src/main/resources/dtds/checkstyle-metadata_1_0.dtd
- net.sf.eclipsecs.doc/src/main/resources/dtds/checkstyle-metadata_1_1.dtd
- net.sf.eclipsecs.doc/src/main/resources/partials/custom-checks.html
- net.sf.eclipsecs.sample/src/net/sf/eclipsecs/sample/checks/checkstyle-metadata.xml
Let all DTDs point to the current host instead of the old sourceforge host.
Verified download from a changed URL works as before.
> Infra: declare all DTDs with checkstyle.org

- pom.xml
The Tycho JGit timestamp provider calculates the timestamp based on the last change of any file in the module. It's therefore okay to be different for different child modules, so it was wrong to disable it in the first place.
The benefit of this timestamp provider is that it leads to the exact same version number each time we re-build the same commit (since that commit defines the timestamp). Without this, rebuilding the same commit leads to the _current_ timestamp (build time) being used, leading to different file names for the same commit.
See https://wiki.eclipse.org/Tycho/Reproducible_Version_Qualifiers for more details.
Tested via local maven build.
> Infra: re-enable tycho jgit timestamp provider

- .ci/validation.sh
- docs/partials/index.html
- docs/sitemap.xml
- net.sf.eclipsecs.doc/pom.xml
- net.sf.eclipsecs.doc/src/main/resources/partials/index.html
- net.sf.eclipsecs.doc/src/main/resources/sitemap.xml
- pom.xml
Instead of adding the current time into the documentation sitemap, use the last change in any file of the docs project. Also use only the date part of the timestamp, not the full second resolution timestamp (using only the date is a valid W3C date format, which is used in sitemaps). That trick avoids vicious circle between committing documentation changes, updating the sitemap, amending to the last commit, updating the sitemap again etc.
That way rebuilding with maven from an existing git commit will no longer lead to unwanted changes in general.
@Calixte @rnveach When this has been merged and you see a locally modified sitemap.xml appearing in the future, then you should commit it, and no longer ignore/replace it, because then there have been changes in the documentation.
> Infra: make documentation timestamp reproducible

- net.sf.eclipsecs.doc/pom.xml
- pom.xml
* exclude surefire (exception in the most recent version)
* exclude checkstyle itself due to sevntu probably depending on old version
Also move all version numbers from child modules into the parents plugin management section, which makes it easier to upgrade everything in one place.
Enable maven-enforcer (it was configured previously, but not executed). The configured rules enforce non snapshot dependencies and a minimum maven version.
> Infra: upgrade maven dependencies

- .project
- net.sf.eclipsecs-feature/.project
- net.sf.eclipsecs-updatesite/.project
- net.sf.eclipsecs.branding/.project
- net.sf.eclipsecs.core/.project
- net.sf.eclipsecs.doc/.project
- net.sf.eclipsecs.sample/.project
- net.sf.eclipsecs.ui/.project
All the projects of the eclipse-cs plugin are both Eclipse projects as well as maven modules. During development in Eclipse the Eclipse internal builder is fully sufficient for building, and running the m2e maven integration builder rather leads to unwanted changes in classpath, settings etc.
I use the same setup (remove m2e builder, but leave m2e nature) in much larger projects under similar conditions.
> Infra: remove the m2e maven builder from all projects

- net.sf.eclipsecs-updatesite/.checkstyle
- net.sf.eclipsecs.branding/.checkstyle
- net.sf.eclipsecs.checkstyle/.checkstyle
- net.sf.eclipsecs.core/.checkstyle
- net.sf.eclipsecs.doc/.checkstyle
- net.sf.eclipsecs.sample/.checkstyle
- net.sf.eclipsecs.ui/.checkstyle
I just had some derived files (in the Eclipse bin directory) showing checkstyle issues. That's not useful, therefore enable the derived files filter for all projects.
> Infra: Filter derived files from own checks

- release.sh
I think the `mvn deploy -P release-composite` command will already generate the docs, so it's not useful to run maven again after.
> infra: remove redundant docs maven build

- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
Make the project name and version number clickable hyperlinks. They open the homepage respectively release notes, using the default browser settings of Eclipse.
For reviewers: It depends on your Eclipse preferences whether this opens in an internal browser in an editor tab or in an external browser as separate process.
> Have hyperlinks in preference page title

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/InternalBrowser.java
Also change the new hyperlinks in the preference page to always use the external browser, because people might not even notice the browser tab _behind_ the preference dialog.
Tested from runtime, opens browser in external process now.
> Issue #510: Open description hyperlinks in external browser

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
Rule descriptions with inline code tags (from Javadoc) rendered those tags verbatim. Replace them by HTML code tags for correct rendering.
before:
after:
> Fix rendering of inline code tags

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/InternalConfigurationEditor.java
Was missing only in 1 of 5 implementation classes.
> Issue #512: Focus config name of internal config editor

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/Messages.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
Don't have the language list in the properties, but rather in code. Also add a localized version of the language name to the dropdown list.
> Issue #506: Available languages must be hard-coded

- docs/sitemap.xml
- net.sf.eclipsecs-updatesite/pom.xml
- net.sf.eclipsecs.doc/pom.xml
- pom.xml
* add more Maven enforcer rules
* pin versions of all required default Maven plugins instead of relying on Maven super POM
* add maven-versions-plugin to plugin management, because that is used to verify and upgrade all these versions
* exclude more maven plugins from m2e execution, they are not needed for the eclipse build
* have all m2e lifecycle mappings in the parent pom, not in child modules
This PR also showcases the previous documentation timestamp changes: The first maven build with all the above changes committed produced new timestamps (because of docs/pom.xml being modified). The sitemap was then amended and will not change any further when building this commit again.
> Infra: more strict/reproducible Maven builds

- .ci/validation.sh
Completely removing the special handling of the sitemap timestamps was wrong. While the other changes in the build avoided that timestamps change with _every_ build, they will still change after real documentation updates (like version number changes).
Therefore re-introduce the special handling, but try it with native git diff arguments.
> Ignore sitemap changes again

- docs/partials/index.html
- docs/partials/install.html
- net.sf.eclipsecs-feature/feature.xml
- net.sf.eclipsecs-updatesite/pom.xml
- net.sf.eclipsecs.doc/src/main/resources/partials/index.html
- net.sf.eclipsecs.doc/src/main/resources/partials/install.html
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
- net.sf.eclipsecs.target/readme.md
> infra: increase minimum required Eclipse version to 2021-06

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetFactory.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetMultiCheck.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetStringArray.java
Ensure that array properties and multi value properties are stored with a normalized ", " separator (comma plus blank) in the config file, independent of how they have been edited in the UI.
That improves readability and comparison of configuration files in the long run.
Example with a bad config file. Opening the editor has the values already normalized and saving would then also fix the config file:
> normalize array properties

- net.sf.eclipsecs.ui/OSGI-INF/l10n/bundle.properties
- net.sf.eclipsecs.ui/plugin.xml
That's the place where all project conversion and configuration contributions of different plugins should appear.
While that's basically a duplication of the sub menus in the Checkstyle command, it's the place where Eclipse developers might look first when trying to enable/disable checkstyle for a project.
The menu items are only visible if all selected projects do/don't have the checkstyle nature and are currently open.
The other menu items in this menu depend on what you have installed, e.g. you might see Xtext, Gradle, Groovy, Maven and other items appear there.
> Add project configuration menu contribution

- config/checkstyle_sevntu_checks.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
This partially reverts 3e27bdc0e329e719140539c70b87f1dbc76c57a5. Boolean expressions with side effects MUST NOT be modified in such a way that short circuit evaluation will remove the side effect. That's a ground rule for all kinds of code optimizations and transformations.
I had to disable one of the sevntu rules, because it's wrong. You cannot move methods to the right of boolean expressions, if those methods have a side effect that changes any global state of the application.
Fixes #559.
Raised https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/1025
> Module configuration editor does not open

- pom.xml
That way any contributor can easily build by invoking maven without any arguments, instead of going through the documentation to find the correct command line.
Also this serves as documentation of being a good Maven project, since it doesn't require "clean" to be used.
> Have a Maven default goal configured

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationWorkingSetEditor.java
https://github.com/checkstyle/eclipse-cs/issues/430
Previously that button was just not layouted in the container widget, but it was actually usable. Now set the widget to invisible, thereby removing it from the tab key cycling and from the button click listener.
> fix #430: set unused button invisible

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationPropertiesDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ExternalFileConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ProjectConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/RemoteConfigurationEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetBoolean.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetMultiCheck.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/FileSetEditDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/MarkerStatsView.java
Explicitly convert to String instead of relying on implicit string concatenation done by the compiler. This would even be worth a checkstyle check.
> Replace confusing type conversion

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/MarkerStatsView.java
> Right align table columns containing numbers

- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
These plugins don't affect the released product, but they are useful when running a development runtime. For instance the layout spy can be used to visually debug the layout of all dialogs etc.
> infra: add development support plugins to target platform

- .derived
When importing all projects in Eclipse, the Maven modules are imported as standalone projects, but also appear as child folders of the root module. That in turn leads to always having each file appear twice when opening the resource selection dialog, running a file search etc.
Mark the child folders in the root module project as derived, which will hide them in most file related operations afterwards.
trying to open a manifest file before and after the change (in the before screenshot all the below ones are unwanted duplicates or temporary files):
> infra: filter duplicated resources

- pom.xml
Upgrading Maven Surefire to a recent version fails with exceptions in the process launching the test process. That's because we have 2 versions of JUnit: 5.10 from Maven and 5.7.1 from the Eclipse target platform. Surefire seems to be confused by that and tries to use the junit-platform-launcher 5.7 from the target platform to launch the 5.10 JUnit during the Maven run.
To avoid this, downgrade the Maven JUnit version to the latest 5.7.x, such that both Maven and Eclipse use the same JUnit version.
Also remove some superfluous configuration.
> infra: downgrade JUnit

- .github/dependabot.yml
* ignore the dependency to the main project in dependabot, because we have to do these changes manually
* remove quotes, gives better syntax highlighting in VS code
* also check the github actions
> Ignore checkstyle dependency update

- net.sf.eclipsecs.checkstyle/.classpath
- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.checkstyle/build.properties
- net.sf.eclipsecs.checkstyle/pom.xml
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
- upgrade-version.build.xml
The new filter works, but every adding/removing of a filter comment only hides/re-adds a violation after purging the Checkstyle cache, not on save like for any other file content change. I'm not sure if that is a problem in the main checkstyle part or in Eclipse-CS. I'd still suggest to commit and release the upgrade and to investigate why cache purging is needed only later.
Fixes #524.
> Upgrade to 10.10.0

- pom.xml
* remove values that are identical to defaults
* have all common configuration and dependencies in pluginManagement to inherit these values in modules
* only have the executions with the specific configuration values remain in plugin section
> infra: simplify maven-checkstyle configuration

- config/checkstyle_sevntu_checks.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/EnhancedTableViewer.java
Fixes #563. Does not affect the XML serialization of the configuration.
> Sort modules in configuration dialog

- .github/dependabot.yml
Since Tycho must be able to load the JUnit runtime support, the version range of JUnit depends on the Tycho version and cannot be upgraded independently.
> infra: ignore JUnit updates in dependabot

- net.sf.eclipsecs.checkstyle/pom.xml
- pom.xml
The unpacking previously happened in the prepage-package lifecycle phase of maven. That's far too late, since other compilation steps require those sources. I had multiple failing local builds because of this.
Until now this only worked correctly because either
* the eclipse builder would compile the depending sources again when the maven build unpacked everything
* the maven build was not fast enough in parallel processing
* the sources were still available locally from the last download, when not using clean in between
Also ensure the order of download and unpack is correct by converting the download to an Ant task and moving it into the same execution. As a side effect, this avoids the download progress messages of the previous download-maven-plugin.
> Fix build order

- pom.xml
* disable a tycho goal which we don't need
* execute the patch creation only once overall, not for each module
Fixes #616
> infra: clean up build goals

- net.sf.eclipsecs-feature/feature.xml
The feature.xml serialization was changed in Eclipse 4.30: https://eclipse.dev/eclipse/news/4.30/pde.php#unnecessary-attributes-removal
This change just stores the feature.xml without any changes, to avoid confusion in the future by other editors when doing actual changes.
> normalize feature.xml to current format

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/Messages.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/TransformCheckstyleRulesJob.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/TransformFormatterRulesJob.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/messages.properties
* Job names are end user visible in the Eclipse UI, therefore just taking some unique identifier without meaning is not correct.
* Always initialize the progress reporting, even if there is nothing to count.
* add icon via job family registration
> Fix configuration transformation jobs

- pom.xml
The Tycho build cannot be run on a Java 21 EE. Document that by means of a Maven enforcer rule (even though Tycho will fail earlier than the rule would be applied).
Can be reverted with the upgrade to a new Tycho major version.
> limit Java EE version

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleMarker.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/RuleGroupMetadata.java
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/plugin.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/MarkerHelpContextProvider.java
* Register a problem marker help provider.
* Calculate a context help topic for each marker and dynamically forward it to the original online help of the related check.
For the end user, pressing F1 on a marker has the result of opening the integrated Eclipse help and showing the checkstyle problem description online.
Fixes #568.
See the modifier order problem marker selected and its help shown:
> Online help for problem markers

- net.sf.eclipsecs.checkstyle/pom.xml
After version upgrades outdated ZIP files from former versions can remain in the local git repository. Get rid of all but the current version when building.
I've noticed these outdated ZIPs several times and instead of continuing to manually delete them, this now automates their deletion.
> infra: avoid outdated local checkstyle ZIPs

- .github/workflows/maven.yml
- net.sf.eclipsecs.target/Maven update check.launch
- net.sf.eclipsecs.target/Maven verify.launch
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
- pom.xml
That is the most recent version as of today. One of the plugins has been moved from tycho.extras to tycho core, therefore the groupid is different.
Also fix the warnings `[WARNING] artifact
foo:bar:p2metadata:10.3.3-SNAPSHOT already attached, replace previous instance` by disabling the default metadata generation. Unfortunately this extra step is necessary when creating source features, since the attaching of metadata needs to be delayed then.
There are new warnings at the very end of the build like `No digest algorithm is available to verify download`. That's an open issue in Tycho but it doesn't break the build, see
https://github.com/eclipse-tycho/tycho/issues/1482
Finally the target platform also needs to be updated. Tycho 3.0 resolves the JUnit classpath container of the .classpath …
> ci: upgrade Tycho to 3.0

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/MarkerHelpContextProvider.java
Some checks have no category and need to be redirected to "misc". Example: UpperEll would wrongly try to open `https://checkstyle.org/checks//upperell.html`. Note the double slash where the category is missing.
> Wrong context help for some uncategorized checks

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/FixCheckstyleMarkersJob.java
The code contained an unchecked cast, and the declaration of the called method had changed in the past, therefore making this incompatible. With the change the menu works fine in a file with multiple fixable violations.
```
java.lang.ClassCastException: class [Lorg.eclipse.ui.IMarkerResolution; cannot be cast to class
[Lnet.sf.eclipsecs.ui.quickfixes.ICheckstyleMarkerResolution; ([Lorg.eclipse.ui.IMarkerResolution; is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6be67f3a; [Lnet.sf.eclipsecs.ui.quickfixes.ICheckstyleMarkerResolution; is in unnamed module of loader
org.eclipse.osgi.internal.loader.EquinoxClassLoader @138bfa5)
at net.sf.eclipsecs.ui.quickfixes.FixCheckstyleMarkersJob.runInUIThread(FixCheckstyleMarkersJob.java:68)
at …
```
> ClassCastException in "Apply all fixes"

- pom.xml
The minimum version of 17 is needed since a while and should have been changed with the Tycho 4 upgrade already. The previous limit of the upper version is no longer needed, all involved tools work fine with 21.
Noticed because my personal default Java is 21 meanwhile, and the build would stop there, for no good reason.
> Lift Java version requirement

- net.sf.eclipsecs-updatesite/pom.xml
- net.sf.eclipsecs.target/Maven update check.launch
- pom.xml
* require Maven 3.9.0, as that is the minimum version required by the Maven plugins that we use
* remove tycho.mode system property, it's deprecated
* relocate the eclipse-run plugin, it's published under the tycho namespace, not the tycho.extras namespace anymore
> Multiple Maven fixes

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/ConfigurationWriter.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/filter/PackageFilterEditor.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/StringLiteralEqualityQuickfix.java
These violations are shown with the most recent 10.14.1 by the eclipse plugin itself (because there was a fix in the "maximum distance between declaration and first usage" check), but are not part of the github verification due to an older version being used there.
@rnveach I guess we still can't do anything about upgrading that 10.4 version in the build? I don't remember exactly but I believe you had told me about either the filters or sevntu project being an issue there.
> Fix new violations

- net.sf.eclipsecs.checkstyle/pom.xml
Previously the sources of the checkstyle library were extracted during the build of the library plugin project, just to make them available in the source feature on the update site.
This is not necessary at all for the plugin to compile and work, and it doesn't help anyone who wants to use the sources of our plugin. Therefore this should just be removed.
> remove source repackaging

- config/checkstyle_checks.xml
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
* don't scan the com.* package hierarchy
* calculate the common root packages of all known packages with checks and metadata instead
* scans only the ...puppycrawl... and net.fs...samplechecks packages in a default developer runtime now
This still finds all relevant metadata files, but takes 480 ms instead of 12 seconds on my laptop.
fixes #515
> only scan relevant classpaths for metadata

- config/checkstyle_checks.xml
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
This adds the sevntu plugin to the target platform. That way launching a debug runtime from the IDE automatically includes sevntu. Have a checkstyle import check to avoid anyone referencing code from the sevntu plugin.
Be aware that this PR includes #681, because changes on the generated .target file are _always_ conflicting. Therefore 681 should be merged first, and then this PR.
> Add sevntu to target platform

- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/.gitignore
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
- upgrade-version.build.xml
* remove and gitignore the checkstyle.jar in eclipsecs.core
* have only the copy in eclipsecs.checkstyle remain
* export packages of transitive dependencies from the eclipsecs.checkstyle project. this is not a good practice, but represents exactly what happened before: consuming the third party dependencies from the checkstyle library
fixes #385
In a follow-up change the re-exported packages should be removed, and instead be replaced by taking the respective libraries into the target platform.
Please be aware this change is based on #684 and #681, therefore those should be merged first.
> Remove duplicate checkstyle.jar

- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/MarkerPropertyPage.java
* convert the marker property labels to selectable text, similar like it is in most file and resource property pages
* remove the suppression help icon (functionality will come back as explicit suppression action in a separate change)
You can now select the text with the mouse:
> selectable marker properties

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
Rule metadata is registered only under the short name of the rule. But markers created for checkstyle violations use the fully qualified name of the checker class instead. Register the fully qualified name as alternative name in the metadata, and the lookup from a stored marker works as expected.
Fixes #397
Looks like this on a stored marker _without running a new analysis_:
Before the fix it would just say "Other" and not find a description.
> Correctly look up metadata from checkstyle marker

- net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/.classpath
- net.sf.eclipsecs.core/.gitignore
- net.sf.eclipsecs.core/META-INF/MANIFEST.MF
- net.sf.eclipsecs.core/build.properties
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
- upgrade-version.build.xml
This reverts commit d74a25f7f64ccaf650d11fa3431e2e2b4216f21f.
The removal of the second copy of the checkstyle.jar worked fine, no compiler issues, no failing tests, and all checks working as intended. However, the configuration dialog didn't display module configurations any more. There is a problem with the re-exported package for the metadata, specifically this line: https://github.com/checkstyle/eclipse-cs/blob/33ce44e8801d824387d4b90bad1e8c096a5ece4c/net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF#L37
I have to investigate more deeply how to make the classpath work correctly without re-exporting that package. Until then, revert the commit, and also add a new check that will throw a runtime error, if no module metadata can be read.
> Revert "remove duplicate checkstyle.jar"

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleMarker.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/Messages.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/MarkerPropertyPage.java
Also show the module id of a rule on the marker property page. The same rule can have multiple different ids in different check configurations. Therefore it seems most simple to store the module id at the time of marker creation instead of later calculating it again.
For old markers or rules without an id, nothing is displayed.
fixes #468
> Show module id on property page

- net.sf.eclipsecs.ui/plugin.xml
f3e15909fc489de6695510b25263d065d44534cc fixed the metadata registration for markers. That also led to the module name in the marker attributes to no longer be named FooCheck, but just Foo. Therefore the marker resolution no longer  matches, and the "Check" suffix needs to be removed there, too.
Looks like this after the fix: 
The light bulbs (and the actual quick fixes) were missing since above commit.
> Re-enable quickfixes

- net.sf.eclipsecs.ui/plugin.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/actions/CheckSelectedFilesAction.java
This adds a command for the already existing action to run checkstyle on the selected resources. That way users can invoke the command also via Ctrl-3 quick assist or via a key binding.
There is no default key binding, as the normal workflow for users is to rely on the Eclipse builder and to not invoke this command manually.
fixes #99
Be aware the shown keybinding is not available by default. I just added that for testing and to illustrate that a keybinding _can_ be given by the user.
> Add command for running checkstyle

- net.sf.eclipsecs.target/Maven target update check.launch
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
- net.sf.eclipsecs.target/pom.xml
- net.sf.eclipsecs.target/target_platform_maven_updates.groovy
Simplify looking for target platform upgrades by injecting them into the Maven object model and let Maven check for available upgrades. That's why this project now has a pom.xml, but is NOT part of the modules list of the parent.
> upgrade external target platform dependencies

- pom.xml
* unbind the default tycho-bnd lifecycle binding, we don't use any bnd instructions
* require same version for all tycho plugins
* exclude eclipsecs.checkstyle from source feature build
> maven cleanup

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckstyleBuilder.java
- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/filters/FilesInSyncFilter.java
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
* refresh SCM change info for every file when filtering
* remove markers from files which don't pass the filter (because those markers are stale)
Changes in target platform are only for local debugging, this has no effect on the published plugin.
Fixes #714
> Refresh SCM filter info correctly

- net.sf.eclipsecs.branding/about.properties
The list of contained third-party software is both incomplete as well as containing a meanwhile unused library. Remove that part of the feature description.
This is the old version of that branding dialog:
> simplify feature branding

- net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/filters/PackageFilter.java
```
[ERROR] src/net/sf/eclipsecs/core/projectconfig/filters/PackageFilter.java:[70,7] (extension) SingleBreakOrContinue: Loops should not contain more than a single "break" or "continue" statement
```
> fix SingleBreakOrContinue

- net.sf.eclipsecs.target/pom.xml
Just to have a more nice Maven output, as all other modules have a better readable name already.
> Add name to target platform module

- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
For newer releases of Eclipse, third party dependencies are typically also available on the main release update site, so we can take them from there instead of from Orbit.
There is no functional change.
> remove Orbit update site

- .mvn/extensions.xml
The Tycho smart builder runs modules in parallel more aggressively than the standard maven parallel builder, thereby saving some build time.
> Use Tycho smart builder

- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
Also replace the outdated apache commons P2 dependency, because its source bundle is not available on the same update site anymore.
> Update Maven dependencies in target platform

- net.sf.eclipsecs.ui/.project
- net.sf.eclipsecs.ui/.settings/org.eclipse.pde.ds.annotations.prefs
- net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
- net.sf.eclipsecs.ui/OSGI-INF/net.sf.eclipsecs.ui.ApplicationStartedHandler.xml
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/ApplicationStartedHandler.java
- net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPlugin.java
Bundle activators should do as little work as possible. Therefore move the registration of the window listener out of the bundle activation and instead have OSGi call back when the application has started. That's later, that improves startup performance and that should avoid race conditions on the workbench display access.
Fixes #781
> Use OSGi service for UI startup handler

- net.sf.eclipsecs.target/net.sf.eclipsecs.target.target
- net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd
@Calixte This might eventually fix your broken import, but it's really just a wild guess. If this doesn't change anything for you, then go ahead with the additional package import.
> explicitly add OSGi annotations to target platform
