pom.xml
And while we are there, add some meta data like license and issue
tracking.
=> update SCM URL in parent pom.xml

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/modifier/ModifierOrderQuickfix.java
The offset reposition calculation didn't include the indentation of the
Javadoc, therefore the offset was wrong by (indentation)*(javadoc lines)
bytes.
To avoid knowing the indentation, the quickfix now calculates the
modifier positions of the AST node instead, since the marker position
must be between the first and last modifier node position.
=> fix #8: modifier order quickfix not working

net.sf.eclipsecs-updatesite/pom.xml, net.sf.eclipsecs.checkstyle/pom.xml, pom.xml
Deploys the update site and update-site.zip to bintray.
Add the following to your .m2/settings.xml:
```
<servers>
<server>
<id>bintray</id>
<username>yourBintrayUser</username>
<password>yourBintrayApiKey</password>
</server>
</servers>
```
Then it's a matter of running `mvn deploy -P bintray` to build and publish the binaries.
@Bananeweizen I sent you an invite for the eclipse-cs organisation on Bintray yesterday, please check if you've received that
@romani I couldn't sent an invite yet, because you don't seem to have an account there
=> Deploy update site and update site archive to bintray using "mvn deploy"

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties
I'm not sure whether additional metadata updates need to be done.
=> fix #39: upgrade to checkstyle 8.8

docs/partials/index.html, docs/partials/releases/8.8.0/release_notes.html, docs/releases.json, docs/sitemap.xml, docs/update/compositeArtifacts.xml, docs/update/compositeContent.xml, net.sf.eclipsecs-feature/feature.xml, net.sf.eclipsecs-feature/pom.xml, net.sf.eclipsecs-updatesite/category.xml, net.sf.eclipsecs-updatesite/pom.xml, net.sf.eclipsecs.branding/META-INF/MANIFEST.MF, net.sf.eclipsecs.branding/pom.xml, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/pom.xml, net.sf.eclipsecs.doc/META-INF/MANIFEST.MF, net.sf.eclipsecs.doc/pom.xml, net.sf.eclipsecs.doc/src/main/resources/partials/index.html, net.sf.eclipsecs.doc/src/main/resources/partials/releases/8.8.0/release_notes.html, net.sf.eclipsecs.doc/src/main/resources/releases.json, net.sf.eclipsecs.sample/META-INF/MANIFEST.MF, net.sf.eclipsecs.sample/pom.xml, net.sf.eclipsecs.target/pom.xml, net.sf.eclipsecs.ui/META-INF/MANIFEST.MF, net.sf.eclipsecs.ui/pom.xml, pom.xml
This is according to the first 6 steps of the release wiki page. I have not attempted updating any binaries or listings.
=> release version 8.8

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/CheckstylePluginPrefs.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/CheckstyleUIPluginPrefs.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetMultiCheck.java
The new API also works with Eclipse 3.x.
=> refactor: replace deprecated instance scope

net.sf.eclipsecs-feature/.project
I missed the feature project in my last cleanup.
=> Remove one more nature

net.sf.eclipsecs-feature/feature.properties, net.sf.eclipsecs.branding/META-INF/MANIFEST.MF, net.sf.eclipsecs.branding/about.properties, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.doc/META-INF/MANIFEST.MF, net.sf.eclipsecs.sample/META-INF/MANIFEST.MF, net.sf.eclipsecs.ui/META-INF/MANIFEST.MF
* rename bundle vendor from URL to Development Team
* update feature URL and branding to checkstyle.org
* reword feature description to avoid plenking
=> remove sourceforge references

net.sf.eclipsecs.core/core.properties, net.sf.eclipsecs.core/plugin.xml, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/filters/FilesOlderThanOneDayFilter.java
Issue https://github.com/checkstyle/eclipse-cs/issues/111
Cherry picked and cleaned up from https://github.com/checkstyle/eclipse-cs/pull/108
=> Fix #111: Add filter for files older than one day

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/messages.properties, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/GraphStatsView.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilter.java
* fix typos, improve wording
* remove useless action icon (it was the one that is generated by the
PDE wizard)
* pie chart tooltip displayed the percentage as wrong absolute number
* disabling a filter did not refresh the pie chart
=> Multiple fixes of violations views

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml
Issue #106 Update to Checkstyle 8.14
=> #106 Update to Checkstyle 8.14

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/blocks/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml
#115 Update to Checkstyle 8.15
=> #115 Update to Checkstyle 8.15

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/modifier/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/modifier/checkstyle-metadata.xml
#125 Update to Checkstyle 8.16
=> #125 Update to Checkstyle 8.16

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/blocks/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/blocks/checkstyle-metadata.xml
#130 Update to Checkstyle 8.17
=> #130 Update to Checkstyle 8.17

README.md
=> minor: extend readme with details on how to install specific version

pom.xml
Upgrade the Maven Tycho build to 1.4. Also add Maven enforcer to require
Maven 3.0 (which is what Tycho requires).
Maven build runs fine locally.
=> upgrade tycho to 1.4

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/filters/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/filters/checkstyle-metadata.xml
Demonstration of new checks:
Configuration:
=> Issue #164: update to Checkstyle 8.23

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/regexp/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/regexp/checkstyle-metadata.xml, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/CheckConfigurationTester.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/TransformCheckstyleRulesJob.java
=> Issue #169: update to Checkstyle 8.25

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties
Fixes #170
Checked functionality of JavadocMethod.
=> Issue #170: update to Checkstyle 8.26

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml
Fixes #193.
Checked functionality of JavadocContentLocation.
=> Issue #193: update to Checkstyle 8.27

.gitignore, net.sf.eclipsecs.doc/docs/.gitignore
=> Issue #192: add net.sf.eclipsecs.doc/docs folder to git to avoid build problems

.travis.yml
detected at https://github.com/checkstyle/eclipse-cs/pull/211#issuecomment-580449484
related to: checkstyle/checkstyle#7444
=> disable google mirror in Travis

pom.xml
Since I had a nasty bug with M2 at work, I'd like this to be upgraded to M3, even though that looks like a very minor thing.
=> Upgrade Maven enforcer plugin

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml
=> Issue #216: update to Checkstyle 8.30

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/design/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/javadoc/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/naming/checkstyle-metadata.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/naming/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/whitespace/checkstyle-metadata.xml
=> Issue #224: update to Checkstyle 8.32

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/coding/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/naming/checkstyle-metadata.xml, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/token.properties
Fixes #243.
Verifying the new Pattern variable definition.
=> Issue #243: update to Checkstyle 8.35

.gitignore, .travis.yml, build-metafile-gen.sh
(this update will be removed ones all metafiles become paert of checkstyle)
=> ci: build metadata-get jar buring a build 

.gitignore, .travis.yml, config/checkstyle_checks.xml, config/checkstyle_sevntu_checks.xml, pom.xml
=> Issue #251: auto generate patch file during maven build

pom.xml
final version from GSoC activity
=> config: bump version of patch-filter to 1.1.0

.gitignore, .travis.yml, build-metafile-gen.sh, net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/ChecksTest.java, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java, net.sf.eclipsecs.ui/.classpath
#256 
New check `RecordComponentNumberCheck` is successfully imported without manual entry.
=> Issue #256: New metadata maintanence method: Fetch directly from checkstyle

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, pom.xml
=> Issue #269: update to Checkstyle 8.36.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
Fixes #276.
Demonstrating new MatchXpath check functionality: 
Note that the UI doesn't allow the user to add the custom message, but once it's added in the XML, it becomes editable there. We can probably improve later.
=> Issue #276: update to Checkstyle 8.39

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #280: update to Checkstyle 8.41

README.md, net.sf.eclipsecs-feature/feature.xml, net.sf.eclipsecs.doc/src/main/resources/partials/index.html, net.sf.eclipsecs.doc/src/main/resources/partials/install.html
I had to drop references to the update-site archives for now as we don't have them anymore.
=> Issue #279: change update-site references

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/RemoteConfigurationType.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/RemoteConfigurationEditor.java
=> Issue #281: Stop using Authenticator for Basic HTTP Auth

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
Fixes #282.
I verified the regression from 8.41 is gone.
=> Issue #282: update to Checkstyle 8.41.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #301: update to Checkstyle 8.44

net.sf.eclipsecs.doc/src/main/resources/partials/index.html
https://github.com/sevntu-checkstyle/sevntu.checkstyle/issues/857#issuecomment-903163309
=> minor: fix the SevNTU update site URL

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
Fixes #308.
This is a minor update. Let me know if you want any screenshot to verify a behavior.
=> Issue #308: update to Checkstyle 8.45.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #313: update to Checkstyle 9.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #323: update to Checkstyle 9.0.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #329: update to Checkstyle 9.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #333: update to Checkstyle 9.2.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #339: update to Checkstyle 9.3

.travis.yml, net.sf.eclipsecs.branding/.classpath, net.sf.eclipsecs.branding/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, net.sf.eclipsecs.doc/.classpath, net.sf.eclipsecs.doc/META-INF/MANIFEST.MF, net.sf.eclipsecs.sample/.classpath, net.sf.eclipsecs.sample/META-INF/MANIFEST.MF, net.sf.eclipsecs.target/Maven update check.launch, net.sf.eclipsecs.target/Update version numbers.launch, net.sf.eclipsecs.target/net.sf.eclipsecs.target.target, net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd, net.sf.eclipsecs.ui/.classpath, net.sf.eclipsecs.ui/META-INF/MANIFEST.MF, pom.xml
=> Issue #340: update to Checkstyle 10.0

net.sf.eclipsecs-updatesite/pom.xml, net.sf.eclipsecs.doc/src/main/resources/partials/index.html, net.sf.eclipsecs.doc/src/main/resources/partials/install.html, net.sf.eclipsecs.target/net.sf.eclipsecs.target.target, net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd, pom.xml
=> Issue #340: change minimum Eclipse version to 2019-06

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #341: update to Checkstyle 10.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #346: update to Checkstyle 10.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #352: update to Checkstyle 10.3

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #354: update to Checkstyle 10.3.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #358: update to Checkstyle 10.3.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #362: update to Checkstyle 10.3.3

.ci/travis.sh, .ci/validation.sh, .travis.yml, docs/partials/releases/8.16.0/release_notes.html
Changing travis to identify a master issue and to assist other PRs.
=> travis updates

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
Issue #322
Broken since introduction of tokenTypesSet in
https://github.com/checkstyle/checkstyle/commit/d038f187190ee5c9d2d55b6aae985b3ec9327614 of the main checkstyle project.
=> Issue #322: NPE on rule configuration

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #364: update to Checkstyle 10.3.4

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #366: update to Checkstyle 10.4

pom.xml
Attempt to fix execution on windows
=> infra: bump patch filter to 1.4

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/CheckstylePlugin.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/CheckstylePluginPrefs.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/CheckerFactory.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/Messages.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/messages.properties, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
This PR suitable for user who using non-english os but want to see different locale violation message
=> violation message locale switchable without restart eclipse

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationWorkingSetEditor.java
Disable the button for making a configuration the default, if it is already the default.
=> Disable "Set to default" if already default

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/builder/Auditor.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/CheckConfigurationFactory.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/BuiltInFilePropertyResolver.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/ConfigurationType.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/StandardPropertyResolver.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/CheckstylePropertyPage.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/SWTUtil.java
=> Issue #440: resolves LogicConditionNeedOptimizationCheck and AvoidConditionInversionCheck

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/ProjectConfigurationFactory.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/actions/CheckstyleTransformingAction.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationConfigureDialog.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilterDialog.java
=> Issue #440: resolves UnnecessaryParenthesesExtended

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/jobs/RunCheckstyleOnFilesJob.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationPropertiesDialog.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/AbstractASTResolution.java
=> Issue #440: resolves StaticMethodCandidate

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/CheckstyleSetting.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/FormatterConfiguration.java
=> Issue #440: resolves EmptyPublicCtorInClassCheck

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/projectconfig/ProjectConfigurationWorkingCopy.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/transformer/CheckstyleSetting.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/RuleConfigurationEditDialog.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetMultiCheck.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/CheckstylePropertyPage.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/filter/PackageFilterEditor.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/quickfixes/coding/DefaultComesLastQuickfix.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/stats/views/internal/CheckstyleMarkerFilter.java
=> Issue #440: resolves ConfusingConditionCheck

config/checkstyle_sevntu_checks.xml, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/CheckConfigurationPropertiesDialog.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/configtypes/ExternalFileConfigurationEditor.java, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/config/widgets/ConfigPropertyWidgetFile.java
Issue #440: resolves AvoidConstantAsFirstOperandInConditionCheck
=>  Issue #440: resolves AvoidConstantAsFirstOperandInConditionCheck 

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/util/table/EnhancedCheckBoxTableViewer.java
=> Issue #440: resolves NumericLiteralNeedsUnderscoreCheck

config/checkstyle_sevntu_checks.xml, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/CheckUtil.java, net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/meta/MetadataFactory.java
All violations resolved from new module.
=> config: synchronizes sevntu config from main repo

config/checkstyle_checks.xml
Issue #451
I found as many as I could that produced no new violations for quicker merge. All synchronized from main repo as it is now.
=> Issue #451: adds multiple modules with no violations

.github/workflows/maven.yml
Adds github workflow to take over for travis for now.
=> config: adds github workflow ci

config/checkstyle_checks.xml
Issue #451
More synchronization with main repo with modules that produce no violations in this project.
=> Issue #451: adds more no violation modules to the checkstyle config

.github/workflows/maven.yml, docs/dtds/checkstyle-metadata_1_0.dtd, docs/dtds/checkstyle-metadata_1_1.dtd
Adding git diff to ensure there are no differences after running install.
Expecting CI to fail currently without fix.
=> config: adds git diff to github workflow

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties
=> Issue #420: update to Checkstyle 10.5.0

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/properties/marker/CheckstyleMarkerPropertyTester.java
=> Issue 467: Avoid property page for runtime error marker

net.sf.eclipsecs.core/.classpath
Those should never have been added.
=> Infra: Remove invalid access rules

net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/actions/ConfigureProjectFromBluePrintAction.java
Use a more specialized dialog to select the soure project for copying a checkstyle configuration. This brings several benefits:
* allows filtering the projects via search mask
* automatically sets selection to first project in list
* filter out closed projects (or otherwise inaccessible projects)
* enable OK button only if there is a selection
The dialog still looks very similar to how it looked before:
=> Improve blueprint selection dialog

net.sf.eclipsecs.ui/OSGI-INF/l10n/bundle.properties, net.sf.eclipsecs.ui/plugin.xml, net.sf.eclipsecs.ui/src/net/sf/eclipsecs/ui/preferences/CheckstylePreferencePage.java
* use better icon
* add description
* use Eclipse terms
Also remove invalid Javadoc part of preference page.
before:
after:
=> Improve preference export description

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #480: update to Checkstyle 10.8.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #482: update to Checkstyle 10.8.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #483: update to Checkstyle 10.9.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #484: update to Checkstyle 10.9.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #547: update to Checkstyle 10.9.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #486: update to Checkstyle 10.9.3

.ci/validation.sh
See https://github.com/checkstyle/eclipse-cs/pull/532#issuecomment-1615281172
=> Infra: ignore changes to docs directory

pom.xml
Extract all versions to properties, and then upgrade them in a second commit.
=> infra: update maven versions

.github/workflows/actionlint.yml
Taken from the main checkstyle repository.
=> infra: add github actions linter

CONTRIBUTING.md, README.md
* Shorten the README. Avoid duplications and complicated sentences.
* Add checkstyle logo to have some graphics.
* Add license.
* Move contribution instructions to separate file.
=> infra: add contribution guide

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #526: update to Checkstyle 10.11.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #533: update to Checkstyle 10.12.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #537: update to Checkstyle 10.12.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #538: update to Checkstyle 10.12.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #550: update to Checkstyle 10.12.3

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #595: update to Checkstyle 10.12.4

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #606: update to Checkstyle 10.12.5

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #608: update to Checkstyle 10.12.6

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #625: update to Checkstyle 10.12.7

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.checkstyle/test/net/sf/eclipsecs/checkstyle/ChecksTest.java, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #641: update to Checkstyle 10.13.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #662: update to Checkstyle 10.14.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #664: update to Checkstyle 10.14.2

net.sf.eclipsecs-updatesite/pom.xml, pom.xml
See https://github.com/checkstyle/eclipse-cs/commit/49972e4099b4899e402c57ce3bd651fb1517c9e0#r140269988
=> use tycho-eclipse-plugin instead of tycho-eclipserun-plugin

pom.xml
We are on Tycho 4 now, where this has long been fixed.
=> remove Tycho 2.x workaround

net.sf.eclipsecs.target/net.sf.eclipsecs.target.tpd, pom.xml
* Use the release instead of nightly of the TPD plugin. There are releases available now since some days.
* upgrade Tycho to 4.0.7
* upgrade JUnit to most recent
=> multiple upgrades

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #683: update to Checkstyle 10.15.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #694: update to Checkstyle 10.16.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #703: update to Checkstyle 10.17.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #734: update to Checkstyle 10.18.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #739: update to Checkstyle 10.18.1

net.sf.eclipsecs.core/src/net/sf/eclipsecs/core/config/configtypes/PropertyUtil.java
```
[ERROR] src/net/sf/eclipsecs/core/config/configtypes/PropertyUtil.java:[149,9] (extension) ForbidCCommentsInMethods: C-style comments (/*...*/) inside method body are not allowed.
```
=> fix ForbidCCommentsInMethods

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #750: update to Checkstyle 10.18.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #763: update to Checkstyle 10.19.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #772: update to Checkstyle 10.20.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #778: update to Checkstyle 10.20.1

Upgrade version numbers.launch
=> Show versions upgrade in favorites menu

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #787: update to Checkstyle 10.20.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #792: update to Checkstyle 10.21.1

net.sf.eclipsecs.doc/src/main/resources/partials/custom-config.html
=> Fix hyperlinks to checkstyle project

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #806: update to Checkstyle 10.21.2

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #820: update to Checkstyle 10.21.3

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #848: update to Checstyle 1.23.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #867: update to Checkstyle 10.25.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #868: update to Checkstyle 10.26.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #869: update to Checkstyle 10.26.1

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #876: update to Checkstyle 11.0.0

net.sf.eclipsecs.checkstyle/.classpath, net.sf.eclipsecs.checkstyle/META-INF/MANIFEST.MF, net.sf.eclipsecs.checkstyle/build.properties, net.sf.eclipsecs.checkstyle/pom.xml, net.sf.eclipsecs.core/.classpath, net.sf.eclipsecs.core/META-INF/MANIFEST.MF, net.sf.eclipsecs.core/build.properties, upgrade-version.build.xml
=> Issue #889: update to Checkstyle 11.0.1
